// 1 - Numbers
TYPE(Zero)
TYPE(One)
TYPE(Two)
TYPE(Half)
TYPE(MinusOne)
TYPE(IntegerShort)
TYPE(IntegerPosBig)
TYPE(IntegerNegBig)
TYPE(RationalShort)
TYPE(RationalPosBig)
TYPE(RationalNegBig)
TYPE(Float)

// 2 - Order dependant expressions
TYPE(Multiplication)
TYPE(Power)
TYPE(Addition)
TYPE(Factorial)
TYPE(Division)
TYPE(Constant)
TYPE(UserSymbol)
TYPE(Sine)
TYPE(Cosine)
TYPE(Tangent)

// 3 - Other expressions in Alphabetic order
TYPE(Abs)
TYPE(ArcCosine)
TYPE(ArcSine)
TYPE(ArcTangent)
TYPE(Complex)
TYPE(Decimal)
TYPE(Derivative)
TYPE(Exponential)
TYPE(Ln)
TYPE(Log)
TYPE(Logarithm)
TYPE(Polynomial)
TYPE(PowerReal)
TYPE(SquareRoot)
TYPE(Subtraction)
TYPE(Trig)
TYPE(TrigDiff)
TYPE(UserFunction)
TYPE(UserSequence)

// 4 - Matrix and vector builtins
TYPE(Dot)
TYPE(Norm)
TYPE(Trace)
TYPE(Cross)
TYPE(Det)
TYPE(Dim)
TYPE(Identity)
TYPE(Inverse)
TYPE(Ref)
TYPE(Rref)
TYPE(Transpose)
TYPE(Matrix)
TYPE(PowerMatrix)

// 5 - Order dependant expressions
TYPE(List)
TYPE(Set)
TYPE(Undefined)

ALIAS(NumberOfNumbersExpression = Float + 1)
ALIAS(NumberOfExpressions = Undefined + 1)
ALIAS(FirstMatrix = Dot)
ALIAS(LastMatrix = PowerMatrix)
