#include "derivation.h"

#include <poincare/src/memory/n_ary.h>
#include <poincare/src/memory/node_iterator.h>

#include "dependency.h"
#include "k_tree.h"
#include "rational.h"
#include "set.h"
#include "simplification.h"
#include "variables.h"

namespace Poincare::Internal {

bool Derivation::ShallowSimplify(Tree* node) {
  // Tree is expected to have been reduced beforehand.
  assert(node->isDiff() || node->isNthDiff());
  const Tree* symbol = node->child(0);
  const Tree* symbolValue = symbol->nextTree();
  const Tree* constDerivand;
  int derivationOrder;
  if (node->isDiff()) {
    derivationOrder = 1;
    constDerivand = symbolValue->nextTree();
  } else {
    const Tree* order = symbolValue->nextTree();
    if (!Integer::Is<uint8_t>(order)) {
      node->cloneTreeOverTree(KUndefUnhandled);
      return true;
    }
    derivationOrder = Integer::Handler(order).to<uint8_t>();
    constDerivand = order->nextTree();
  }
  Tree* derivand = constDerivand->clone();
  int currentDerivationOrder = derivationOrder;
  while (currentDerivationOrder > 0) {
    Tree* derivative = Derivate(derivand, symbolValue, symbol);
    if (!derivative) {
      // TODO is it worth to save the partial derivation if any ?
      derivand->removeTree();
      return false;
    }
    if (derivative->isDependency()) {
      /* Remove the dependencies created during derivation reduction since they
       * were just generated by the calculation process and should already be
       * included in the derivand dependency.
       * TODO: Ensure the calculation process cannot generate useful
       * dependencies.
       * Example: 3x is derivated to 0*x+3*1 because we use the u'v+uv' formula.
       * So a dependency is created on x (because of 0*x), but 3x is already a
       * dependency. */
      derivative->moveTreeOverTree(derivative->child(0));
    }
    if (derivative->isZero()) {
      currentDerivationOrder = 0;
    } else {
      currentDerivationOrder--;
    }
    derivand->removeTree();
  }

  Variables::LeaveScopeWithReplacement(derivand, symbolValue, true);

  // Add a dependency on derivand if anything has been derived.
  if (currentDerivationOrder < derivationOrder && !derivand->isUndefined()) {
    SharedTreeStack->push<Type::Set>(1);
    Variables::LeaveScopeWithReplacement(constDerivand->clone(), symbolValue,
                                         false);
    derivand->cloneNodeAtNode(KDep);
  }

  node->moveTreeOverTree(derivand);
  return true;
}

// Derivate derivand preserving scope (V0^2 is derived to 2*V0).
Tree* Derivation::Derivate(const Tree* derivand, const Tree* symbolValue,
                           const Tree* symbol) {
  if (derivand->treeIsIdenticalTo(KVarX)) {
    return (1_e)->clone();
  }
  if (derivand->isRandomNode()) {
    // Do not handle random nodes in derivation.
    return KUndefUnhandled->clone();
  }
  int numberOfChildren = derivand->numberOfChildren();
  if (numberOfChildren == 0) {
    return (0_e)->clone();
  }

  Tree* result = SharedTreeStack->push<Type::Add>(0);
  const Tree* derivandChild = derivand->child(0);
  /* D(f(g0(x),g1(x), ...)) = Sum(D(gi(x))*Di(f)(g0(x),g1(x), ...))
   * With D being the Derivative and Di being the partial derivative on
   * parameter i. */
  for (int i = 0; i < numberOfChildren; i++) {
    NAry::SetNumberOfChildren(result, i + 1);
    Tree* mult = SharedTreeStack->push<Type::Mult>(1);
    if (!Derivate(derivandChild, symbolValue, symbol)) {
      // Could not derivate, preserve D(gi(x))
      Tree* preservedDerivative = SharedTreeStack->push(Type::Diff);
      symbol->clone();
      symbolValue->clone();
      derivandChild->clone();
      // EnterScope here since scope is preserved in Derivation::Derivate.
      Variables::EnterScope(preservedDerivative);
    }
    if (!ShallowPartialDerivate(derivand, i)) {
      // Cancel current derivation.
      result->removeTree();
      return nullptr;
    }
    NAry::SetNumberOfChildren(mult, 2);
    Simplification::ShallowSystematicReduce(mult);
    derivandChild = derivandChild->nextTree();
  }
  Simplification::ShallowSystematicReduce(result);
  return result;
}

bool Derivation::ShallowPartialDerivate(const Tree* derivand, int index) {
  switch (derivand->type()) {
    case Type::Mult: {
      // Di(x0 * x1 * ... * xi * ...) = x0 * x1 * ... * xi-1 * xi+1 * ...
      int numberOfChildren = derivand->numberOfChildren();
      assert(numberOfChildren > 1 && index < numberOfChildren);
      Tree* mult;
      if (numberOfChildren > 2) {
        mult = SharedTreeStack->push<Type::Mult>(numberOfChildren - 1);
      }
      for (std::pair<const Tree*, int> indexedNode :
           NodeIterator::Children<NoEditable>(derivand)) {
        if (indexedNode.second != index) {
          indexedNode.first->clone();
        }
      }
      if (numberOfChildren > 2) {
        Simplification::ShallowSystematicReduce(mult);
      }
      return true;
    }
    case Type::Add:
      // Di(x0 + x1 + ... + xi + ...) = 1
      SharedTreeStack->push(Type::One);
      return true;
    case Type::Exp:
      // Di(exp(x)) = exp(x)
      derivand->clone();
      return true;
    case Type::LnReal:
    case Type::Ln: {
      // Di(ln(x)) = 1/x
      Tree* power = SharedTreeStack->push(Type::Pow);
      derivand->child(0)->clone();
      SharedTreeStack->push(Type::MinusOne);
      Simplification::ShallowSystematicReduce(power);
      return true;
    }
    case Type::Trig:
      // Di(Trig(x, n)) = Trig(x, n-1)
    case Type::Pow: {
      // Di(x^n) = n*x^(n-1)
      // Second parameter cannot depend on symbol.
      assert(!Variables::HasVariables(derivand->child(1)));
      if (index == 1) {
        SharedTreeStack->push(Type::Zero);
        return true;
      }
      Tree* multiplication;
      if (derivand->isPow()) {
        multiplication = SharedTreeStack->push<Type::Mult>(2);
        SharedTreeStack->clone(derivand->child(1));
      }
      Tree* newNode = SharedTreeStack->clone(derivand, false);
      derivand->child(0)->clone();
      Tree* addition = SharedTreeStack->push<Type::Add>(2);
      SharedTreeStack->clone(derivand->child(1));
      SharedTreeStack->push(Type::MinusOne);
      Simplification::ShallowSystematicReduce(addition);
      Simplification::ShallowSystematicReduce(newNode);
      if (derivand->isPow()) {
        Simplification::ShallowSystematicReduce(multiplication);
      }
      return true;
    }
    default:
      return false;
  }
}

}  // namespace Poincare::Internal
