SFLAGS += -Ipoincare/include

poincare_src += $(addprefix poincare/src/old/,\
  junior_layout.cpp \
  layout.cpp \
  layout_node.cpp \
)

poincare_src += $(addprefix poincare/src/old/,\
  aliases_list.cpp \
  pool_checkpoint.cpp \
  circuit_breaker_checkpoint.cpp \
  exception_checkpoint.cpp \
  helpers.cpp \
  xnt_helpers.cpp \
)

poincare_src += $(addprefix poincare/src/old/,\
  absolute_value.cpp \
  addition.cpp \
  approximation_helper.cpp \
  arc_cosecant.cpp \
  arc_cosine.cpp \
  arc_cotangent.cpp \
  arc_secant.cpp \
  arc_sine.cpp \
  arc_tangent.cpp \
  arithmetic.cpp \
  array.cpp \
  based_integer.cpp \
  binomial_coefficient.cpp \
  boolean.cpp \
  ceiling.cpp \
  comparison.cpp \
  complex.cpp \
  complex_argument.cpp \
  complex_cartesian.cpp \
  computation_context.cpp \
  conic.cpp \
  conjugate.cpp \
  constant.cpp \
  context.cpp \
  cosecant.cpp \
  cosine.cpp \
  cotangent.cpp \
  decimal.cpp \
  dependency.cpp \
  derivative.cpp \
  determinant.cpp \
  dimension.cpp \
  distribution_dispatcher.cpp \
  division.cpp \
  division_quotient.cpp \
  division_remainder.cpp \
  empty_context.cpp \
  empty_expression.cpp \
  evaluation.cpp \
  expression.cpp \
  expression_node.cpp \
  expression_node_properties.cpp \
  factor.cpp \
  factorial.cpp \
  float.cpp \
  float_list.cpp \
  floor.cpp \
  frac_part.cpp \
  function.cpp \
  great_common_divisor.cpp \
  hyperbolic_arc_cosine.cpp \
  hyperbolic_arc_sine.cpp \
  hyperbolic_arc_tangent.cpp \
  hyperbolic_cosine.cpp \
  hyperbolic_sine.cpp \
  hyperbolic_tangent.cpp \
  hyperbolic_trigonometric_function.cpp \
  imaginary_part.cpp \
  infinity.cpp \
  integer.cpp \
  integral.cpp \
  junior_expression.cpp \
  least_common_multiple.cpp \
  list.cpp \
  list_access.cpp \
  list_complex.cpp \
  list_maximum.cpp \
  list_mean.cpp \
  list_median.cpp \
  list_minimum.cpp \
  list_product.cpp \
  list_sample_standard_deviation.cpp \
  list_sequence.cpp \
  list_sort.cpp \
  list_standard_deviation.cpp \
  list_sum.cpp \
  list_variance.cpp \
  logarithm.cpp \
  logical_operator.cpp \
  matrix.cpp \
  matrix_complex.cpp \
  matrix_echelon_form.cpp \
  matrix_identity.cpp \
  matrix_inverse.cpp \
  matrix_reduced_row_echelon_form.cpp \
  matrix_row_echelon_form.cpp \
  matrix_trace.cpp \
  matrix_transpose.cpp \
  mixed_fraction.cpp \
  multiplication.cpp \
  n_ary_expression.cpp \
  n_ary_infix_expression.cpp \
  naperian_logarithm.cpp \
  nonreal.cpp \
  nth_root.cpp \
  number.cpp \
  opposite.cpp \
  parametered_expression.cpp \
  parenthesis.cpp \
  percent.cpp \
  permute_coefficient.cpp \
  piecewise_operator.cpp \
  point.cpp \
  point_evaluation.cpp \
  point_of_interest.cpp \
  polynomial.cpp \
  power.cpp \
  preferences_in_storage.cpp \
  product.cpp \
  randint.cpp \
  randint_no_repeat.cpp \
  random.cpp \
  rational.cpp \
  real_part.cpp \
  rightwards_arrow_expression.cpp \
  round.cpp \
  secant.cpp \
  sequence.cpp \
  serialization_helper.cpp \
  sign_function.cpp \
  simplification_helper.cpp \
  sine.cpp \
  solver.cpp \
  solver_algorithms.cpp \
  square_root.cpp \
  store.cpp \
  subtraction.cpp \
  sum.cpp \
  sum_and_product.cpp \
  symbol.cpp \
  symbol_abstract.cpp \
  tangent.cpp \
  pool_handle.cpp \
  pool_object.cpp \
  pool.cpp \
  trigonometry.cpp \
  trigonometry_cheat_table.cpp \
  undefined.cpp \
  unit.cpp \
  unit_convert.cpp \
  variable_context.cpp \
  vector_cross.cpp \
  vector_dot.cpp \
  vector_norm.cpp \
  zoom.cpp \
)


tests_src += $(addprefix poincare/test/old/,\
  helper.cpp \
  approximation.cpp \
  derivative.cpp \
  parsing.cpp \
  simplification.cpp \
)

poincare_bench_src = $(addprefix poincare/src/,\
  init.cpp \
  preferences.cpp \
  print_float.cpp \
)

poincare_bench_src = $(addprefix poincare/src/old/,\
  pool_checkpoint_dummy.cpp \
  helpers.cpp \
  integer.cpp \
  preferences_no_storage.cpp \
  serialization_helper.cpp \
  pool_handle.cpp \
  pool_object.cpp \
  pool.cpp \
)


poincare_src += $(addprefix poincare/src/,\
  expression/advanced_simplification.cpp \
  expression/advanced_operation.cpp \
  expression/algebraic.cpp \
  expression/aliases.cpp \
  expression/arithmetic.cpp \
  expression/approximation.cpp \
  expression/approximation_derivative.cpp \
  expression/approximation_helpers.cpp \
  expression/approximation_integral.cpp \
  expression/approximation_prepare.cpp \
  expression/approximation_power.cpp \
  expression/approximation_trigonometry.cpp \
  expression/beautification.cpp \
  expression/binary.cpp \
  expression/builtin.cpp \
  expression/comparison.cpp \
  expression/continuity.cpp \
  expression/conversion.cpp \
  expression/decimal.cpp \
  expression/degree.cpp \
  expression/dependency.cpp \
  expression/derivation.cpp \
  expression/dimension.cpp \
  expression/dimension_vector.cpp \
  expression/float.cpp \
  expression/infinity.cpp \
  expression/integer.cpp \
  expression/integer_serialization.cpp \
  expression/list.cpp \
  expression/logarithm.cpp \
  expression/matrix.cpp \
  expression/metric.cpp \
  expression/number.cpp \
  expression/parametric.cpp \
  expression/physical_constant.cpp \
  expression/polynomial.cpp \
  expression/projection.cpp \
  expression/random.cpp \
  expression/rational.cpp \
  expression/set.cpp \
  expression/sign.cpp \
  expression/simplification.cpp \
  expression/solver.cpp \
  expression/symbol.cpp \
  expression/systematic_addition.cpp \
  expression/systematic_operation.cpp \
  expression/systematic_multiplication.cpp \
  expression/trigonometry.cpp \
  expression/undefined.cpp \
  expression/unit.cpp \
  expression/unit_representatives.cpp \
  expression/variables.cpp \
  expression/vector.cpp \
  init.cpp \
  layout/app_helpers.cpp \
  layout/autocompleted_pair.cpp \
  layout/code_point_layout.cpp \
  layout/cursor_motion.cpp \
  layout/empty_rectangle.cpp \
  layout/grid.cpp \
  layout/input_beautification.cpp \
  layout/layout_cursor.cpp \
  layout/layout_selection.cpp \
  layout/layout_span.cpp \
  layout/layout_span_decoder.cpp \
  layout/layoutter.cpp \
  layout/multiplication_symbol.cpp \
  layout/parser.cpp \
  layout/parsing/helper.cpp \
  layout/parsing/rack_parser.cpp \
  layout/parsing/tokenizer.cpp \
  layout/rack_from_text.cpp \
  layout/rack_layout.cpp \
  layout/rack_layout_decoder.cpp \
  layout/render.cpp \
  layout/serialize.cpp \
  layout/xnt.cpp \
  memory/tree_stack.cpp \
  memory/tree_stack_checkpoint.cpp \
  memory/n_ary.cpp \
  memory/pattern_matching.cpp \
  memory/tree.cpp \
  memory/tree_ref.cpp \
  memory/value_block.cpp \
  memory/visualization.cpp \
  preferences.cpp \
  print.cpp \
  print_float.cpp \
  range.cpp \
)

poincare_src += $(addprefix poincare/src/numeric/,\
  beta_function.cpp \
  erf_inv.cpp \
  regularized_gamma_function.cpp \
  regularized_incomplete_beta_function.cpp \
  roots.cpp \
  solver.cpp \
  solver_algorithms.cpp \
  statistics_dataset.cpp\
  statistics_dataset_column.cpp\
)

poincare_src += $(addprefix poincare/src/probability/,\
  binomial_distribution.cpp \
  cdf_method.cpp \
  cdf_range_method.cpp \
  chi2_distribution.cpp \
  discrete_distribution.cpp \
  distribution.cpp \
  distribution_method.cpp \
  domain.cpp \
  exponential_distribution.cpp \
  fisher_distribution.cpp \
  geometric_distribution.cpp \
  hypergeometric_distribution.cpp \
  inv_method.cpp \
  normal_distribution.cpp \
  pdf_method.cpp \
  poisson_distribution.cpp \
  student_distribution.cpp \
  uniform_distribution.cpp \
)

tests_src += $(addprefix poincare/src/,\
  layout/parsing/latex_parser.cpp \
)

tests_src += $(addprefix poincare/test/,\
  approximation.cpp \
  beautification.cpp \
  comparison.cpp \
  dimension.cpp \
  distribution.cpp \
  erf_inv.cpp \
  expression_comparison.cpp \
  expression_to_layout.cpp \
  float_helper.cpp \
  layout.cpp \
  helper.cpp \
  integer.cpp \
  k_tree.cpp \
  latex_parser.cpp \
  layout_to_expression.cpp \
  match.cpp \
  matrix.cpp \
  memory_elements.cpp \
  memory_edition.cpp \
  n_ary.cpp \
  numeric_solver.cpp \
  parse.cpp \
  polynomial.cpp \
  projection.cpp \
  print.cpp \
  print_float.cpp \
  range.cpp \
  rational.cpp \
  regularized_function.cpp \
  roots.cpp \
  set.cpp \
  sign.cpp \
  simplification.cpp \
  solver.cpp \
)

tests_src += $(poincare_src)

ifeq ($(DEBUG),1)
  ifeq ($(PLATFORM),simulator)
    POINCARE_TREE_LOG ?= 1
  endif
endif

ifdef POINCARE_TREE_LOG
SFLAGS += -DPOINCARE_TREE_LOG=$(POINCARE_TREE_LOG)
endif
